- **학습 목표**: 행렬 곱·전치·역행렬을 코드로 직접 실행해보고, 그 결과가 "기하학적으로" 무엇을 의미하는지 눈으로 확인한다.
- **핵심 개념**: `A @ v`는 벡터 `v`를 행렬 `A`가 정의하는 변환(회전·스케일링 등)으로 옮기는 것입니다. 역행렬이 없다는 것은 그 변환이 정보를 "압축"해서 되돌릴 수 없다는 뜻입니다.
- **구현 과제 (스스로 작성)**: 아래 다섯 가지를 확인하는 스크립트를 작성하세요. 함수로 나누든 순서대로 스크립트로 짜든 자유입니다.
  1. 임의의 2×2 행렬 `A`, `B`를 정의하고 `A @ B`를 계산해 출력한다.
  2. 단위벡터 `[1,0]`, `[0,1]`에 `A`를 적용한 결과가 `A`의 첫 번째/두 번째 열과 같은지 비교한다.
  3. `A.T`(전치)를 출력한다.
  4. `A`의 역행렬을 계산하고, `A @ A_inv`가 (부동소수점 오차 범위 내에서) 단위행렬인지 `np.allclose` 또는 `np.round`로 확인한다.
  5. 두 번째 행이 첫 번째 행의 배수인 "특이(singular) 행렬"을 하나 만들어 `np.linalg.det()`으로 행렬식을 확인하고, 역행렬 계산을 시도했을 때 어떤 에러가 나는지 관찰한다.
- **확인 질문**:
  - `A @ B`는 기하학적으로 "B를 먼저 적용하고 A를 적용하는 것"이라는 말이 왜 맞는지, 위 2번 결과로 설명할 수 있는가?
  - 행렬식이 0이면 왜 역행렬이 존재하지 않는가?

In [25]:
import numpy as np

a = np.array([[1,4],[5,2]])
b = np.array([[6,5],[2,4]])
e = np.array([[1,0],[0,1]])

print(f"Muliplication with unit vector(e) : A @ E = \n{np.dot(a,e)}")
print(f"Muliplication : A @ B = \n{a@b}")
print(f"transposed matrix : A^T = \n{np.transpose(a)}")
print(f"inverse matrix : A^-1 = \n{np.linalg.inv(a)}")
print(f"Muliplication with inverse matrix : A @ A^-1 = \n{np.dot(a,np.linalg.inv(a))}")

"""
numpy.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)[source]
returns True if two arrays are element-wise equal within a tolerance.

numpy.round(a, decimals=0, out=None)[source]
Evenly round to the given number of decimals.
"""
print(f"Check if A @ A^-1 is close to unit matrix(using np.allclose) : {np.allclose(np.dot(a,np.linalg.inv(a)),e)}")
print(f"Check if A @ A^-1 is close to unit matrix(using np.round) : {np.round(np.dot(a,np.linalg.inv(a)))==e}")

#singular matrix
s = np.array([[1,2],[2,4]])
print(f"Determinant of singular matrix(s) : (np.linalg.det(s)) = {np.linalg.det(s)}")
try:
  print(f"Inverse of singular matrix(s) : (np.linalg.inv(s)) = {np.linalg.inv(s)}")
except Exception as ex:
  print(f"Inverse of singular matrix(s) : (np.linalg.inv(s)) = np.linalg.inv(s)")
  print(ex)

Muliplication with unit vector(e) : A @ E = 
[[1 4]
 [5 2]]
Muliplication : A @ B = 
[[14 21]
 [34 33]]
transposed matrix : A^T = 
[[1 5]
 [4 2]]
inverse matrix : A^-1 = 
[[-0.11111111  0.22222222]
 [ 0.27777778 -0.05555556]]
Muliplication with inverse matrix : A @ A^-1 = 
[[1. 0.]
 [0. 1.]]
Check if A @ A^-1 is close to unit matrix(using np.allclose) : True
Check if A @ A^-1 is close to unit matrix(using np.round) : [[ True  True]
 [ True  True]]
Determinant of singular matrix(s) : (np.linalg.det(s)) = 0.0
Inverse of singular matrix(s) : (np.linalg.inv(s)) = np.linalg.inv(s)
Singular matrix
