- **학습 목표**: 특이(singular) 행렬에 영공간이 실제로 존재함을 코드로 확인하고, 그것이 "정보가 사라지는 방향"이라는 의미와 연결할 수 있다.
- **핵심 개념**: 영공간에 속한 벡터 `v`는 `A @ v = 0`입니다. 즉 `A`라는 변환을 거치면 `v`의 정보가 완전히 사라집니다. 되돌릴 수 없으니 역행렬도 없습니다. PCA에서는 공분산 행렬이 특이하면 일부 고유값이 0이 되고, 그 방향에는 데이터가 전혀 퍼져 있지 않다는 뜻이 됩니다.
- **구현 과제 (스스로 작성)**:

In [ ]:
import scipy.linalg
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def explore_lu(A: np.ndarray):
  """
  요구사항:
  - scipy.linalg.lu로 A를 P, L, U로 분해한다.
  - P @ L @ U 가 원래 A와 같은지 np.allclose로 검증하고 결과를 출력한다.
  - L이 하삼각, U가 상삼각 형태인지 눈으로 확인할 수 있게 출력한다.
  """
  p, l, u = scipy.linalg.lu(A)
  print(np.allclose(p@l@u, A))
  print(l)
  print(u)


def explore_null_space(B: np.ndarray):
  """
  요구사항:
  - 일부러 선형 종속인 행(예: 어떤 행이 다른 행의 배수)을 가진 3x3 행렬 B를 만든다.
  - np.linalg.matrix_rank(B)를 출력해 rank가 3보다 작음을 확인한다.
  - scipy.linalg.null_space(B)로 영공간 basis를 구한다.
  - basis 벡터 v 하나에 대해 B @ v 가 0 벡터에 가까운지 np.allclose(..., atol=1e-8)로 검증한다.
  """
  rank = np.linalg.matrix_rank(B)
  print(f"Rank(B) = {rank}")
  null_space_basis = scipy.linalg.null_space(B)
  print(null_space_basis)
  print(np.allclose(B @ null_space_basis, np.zeros_like(null_space_basis)))


A = np.random.rand(4, 4)
explore_lu(A)

B = np.random.rand(3,3)
B[:, 2] = B[:, 0] + B[:, 1]
explore_null_space(B)

True
[[ 1.          0.          0.          0.        ]
 [ 0.68876714  1.          0.          0.        ]
 [ 0.48233061 -0.76953225  1.          0.        ]
 [ 0.71039535  0.14659301 -0.31249813  1.        ]]
[[ 0.94989092  0.72617237  0.84465956  0.88328329]
 [ 0.         -0.33052681 -0.40788634  0.05732253]
 [ 0.          0.         -0.5263876  -0.21093256]
 [ 0.          0.          0.          0.28301782]]
Rank(B) = 2
[[ 0.57735027]
 [ 0.57735027]
 [-0.57735027]]
True


- **확인 질문**:
  - `rank(B)`가 2이고 B가 3×3일 때, 영공간의 차원은 몇인가? 실제 `null_space(B)`의 shape와 일치하는가?
  - 만약 샘플 수가 차원 수보다 적다면(예: 데이터 50개, 특성 100개) 공분산 행렬의 rank는 최대 얼마인가? PCA에서 어떤 문제가 생기는가?

B가 3x3일 때, 영공간의 차원은 1. 실제 null_space(B).shape도 1.
만약 샘플 수가 차원 수보다 적다면, 공분산 행렬의 rank는 샘플의 차원과 같아지게 된다.